spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      uri: mongodb+srv://mouhanedmliki66_db_user:v9s8qfK0MEiSLKQL@cluster0.s3inqkc.mongodb.net/gestion_soutenances_auth?appName=Cluster0
      database: gestion_soutenances_auth
      auto-index-creation: true

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 96P0FrII0AVNGDBdY+EIF9EY/WQk4FKLqRV+ivPvsmhUyegmWPXXIrQkF1rjwrxg3E+NeDXlkznMLcvNx1uyg==
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG
    com.microservices: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
  packages-to-scan: com.microservices.auth_service
  default-consumes-media-type: application/json
