# ============================================
# APPLICATION NAME
# ============================================
spring.application.name=planning-service

# ============================================
# SERVER CONFIGURATION
# ============================================
server.port=8083

# ============================================
# DATASOURCE (PostgreSQL)
# ============================================
spring.data.mongodb.host=planning-cluster.o7nyftw.mongodb.net
spring.data.mongodb.port=27017
spring.data.mongodb.database=planning_db
spring.data.mongodb.username=ahlemhorchani701_db_user
spring.data.mongodb.password=hd9L9KqaFGEylRhk
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.ssl=true
# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# LOGGING
# ============================================
logging.level.com.soutenance.planning=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE