# ============================================
# SERVER CONFIGURATION
# ============================================
server:
  port: 8083

# ============================================
# DATASOURCE (MongoDB Atlas)
# ============================================
spring:
  application:
    name: planning-service
  data:
    mongodb:
      # Option 1 : URI unique (RECOMMANDÉ)
      uri: mongodb+srv://ahlemhorchani701_db_user:hd9L9KqaFGEylRhk@planning-cluster.o7nyftw.mongodb.net/planning_db?retryWrites=true&w=majority&appName=planning-cluster

# ============================================
# LOGGING
# ============================================
logging:
  level:
    com.soutenance.planning: DEBUG
    org.springframework.web: INFO
    org.springframework.data.mongodb.core: DEBUG