# ============================================
# SERVER CONFIGURATION
# ============================================
server:
  port: 8083

# ============================================
# DATASOURCE (MongoDB)
# ============================================
spring:
  application:
    name: planning-service
  data:
    mongodb:
      host: planning-cluster.o7nyftw.mongodb.net
      port: 27017
      database: planning_db
      username: ahlemhorchani701_db_user
      password: hd9L9KqaFGEylRhk
      authentication-database: admin
      ssl: true

# ============================================
# LOGGING
# ============================================
logging:
  level:
    com.soutenance.planning: DEBUG
    org.springframework.web: INFO