spring:
  application:
    name: jury-service
  data:
    mongodb:
      uri: mongodb+srv://ahlemhorchani701_db_user:hd9L9KqaFGEylRhk@planning-cluster.o7nyftw.mongodb.net/jury_service?retryWrites=true&w=majority&appName=planning-cluster

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true



logging:
  level:
    com.microservices.jury_service: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG